### ISSUE TITLE
connect ECONNREFUSED

### ISSUE THREAD

**Issue by arall** [qrpike/spotify-playlist-downloader#8] opened 2015-05-16 09:19 UTC
I get this error when I try to run the example:

```
spd -u myUsername -p myPassword -l spotify:user:spotify:playlist:06KmJWiQhL0XiV6QQAHsmw
```
```
Downloader App Started..
Error logging in... (Error: connect ECONNREFUSED)
```

**Comment by watsonbox** [comment] 2015-05-18 11:42
Same here on both OSX 10.9.5 and 10.10.3.

**Comment by gtothesquare** [comment] 2015-05-18 15:04
Well, the problem is not with this module but with https://github.com/TooTallNate/node-spotify-web . I tried authenticating with spotify-web and I get the `ECONNREFUED` error. My guess is that they changed something with the protocol and requires some token.

**Comment by gtothesquare** [comment] 2015-05-18 15:06
or regarding this issue report https://github.com/TooTallNate/node-spotify-web/issues/107

**Comment by gtothesquare** [comment] 2015-06-02 19:41
Ok found the problem, currently this only works with node 10.x (i tested it with node v0.10.36). If you upgrade your node instalation to 0.12.x then I suggest you install nvm have multiple version of node.

@watsonbox  @arall Once installed make the switch to 0.10.36 using nvm and then unistall  spotify-playlist-downloader global package. Now install again with. This last part is important because the package will be installed using node 10, if not the proto thingy will not work correctly.

**Comment by arall** [comment] 2015-06-07 11:11
Perfect, it works fine now. Thanks @gtothesquare

**Comment by tristan1990** [comment] 2015-06-13 13:08
@gtothesquare Is yours still working. I'm having problems, even when I have reinstalled 0.10.36 with nvm..
![spotifydownloads bash 92x34](https://cloud.githubusercontent.com/assets/5122381/8144408/a15fb22e-11d5-11e5-8b52-c01b96cec637.png)

**Comment by gtothesquare** [comment] 2015-06-14 12:29
@tristan1990 yeah still working. However I saw from your other comment you figured it out ?

**Comment by tristan1990** [comment] 2015-06-14 17:51
@gtothesquare Yes, all figured out. I had to install FFPEG. Is the limit set to 100 tracks by the Spotify API?

Thanks

**Comment by gtothesquare** [comment] 2015-06-14 20:06
Cool. That I don't know off. Might be a song that is your problem :)

**Comment by roshanr10** [comment] 2015-06-21 22:15
@tristan1990 I believe the limit is closer to 200 as described within their documentation. Have you solved the issue?

https://developer.spotify.com/web-api/

**Comment by gtothesquare** [comment] 2015-07-15 08:07
@arall can you close this issue?

**Closed** 2015-07-15 09:15 UTC
